apiVersion: cls.tencentcloud.crossplane.io/v1alpha1
kind: Index
metadata:
  annotations:
    meta.upbound.io/example-id: cls/v1alpha1/index
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    includeInternalFields: true
    metadataFlag: 1
    rule:
    - dynamicIndex:
      - status: true
      fullText:
      - caseSensitive: true
        containZH: true
        tokenizer: ${local.tokenizer_value}
      keyValue:
      - caseSensitive: true
        keyValues:
        - key: hello
          value:
          - containZH: true
            sqlFlag: true
            tokenizer: ${local.tokenizer_value}
            type: text
        - key: world
          value:
          - containZH: true
            sqlFlag: true
            tokenizer: ${local.tokenizer_value}
            type: text
      tag:
      - caseSensitive: true
        keyValues:
        - key: terraform
          value:
          - containZH: true
            sqlFlag: true
            tokenizer: ${local.tokenizer_value}
            type: text
    status: true
    topicIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: cls.tencentcloud.crossplane.io/v1alpha1
kind: Logset
metadata:
  annotations:
    meta.upbound.io/example-id: cls/v1alpha1/index
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    logsetName: tf_example
    tags:
      demo: test

---

apiVersion: cls.tencentcloud.crossplane.io/v1alpha1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: cls/v1alpha1/index
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    autoSplit: false
    describes: Test Demo.
    hotPeriod: 10
    logsetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    maxSplitPartitions: 20
    partitionCount: 1
    period: 30
    storageType: hot
    tags:
      test: test
    topicName: tf_example
